### ISSUE TITLE
Direct Download of Data from Web Browser

### ISSUE THREAD

**Issue by happyimadesignr** [DataBiosphere/data-browser#102]
Here are examples from Paolo. He says he has downloaded terabytes of data from these sites.

https://genome.ucsc.edu/
https://www.ncbi.nlm.nih.gov/guide/data-software/

He also says: "As you will see, contrary to the HCA preview, both of them let you download data directly from the browser without having to install or setup anything. They also give command line tips to do the download more efficiently, but using only tools that are available on all Linux machines and on many other non-Linux machines (e. g.ftp, rsync command)."

┆Issue Number: HCAB-45

**Comment by theathorn** [comment]
Following user feedback with Adrienne of CZI, the suggestion is:
   - Keep the Files tab and allow user to click on filename link
   - If file is < 1GB allow direct download from browser, else redirect to manifest+cli download.

Question: Paolo's comment suggests direct browser download is possible for very large files?

**Comment by briandoconnor** [comment]
A couple things:

* I think it will work great for small files, need to make sure Carlos' files API endpoint supplies file size.  And then a small amount of javascript can be used to either make the URL generation request and download or pop up an alert saying "this file is too big"
* it might be worth while to include another button that says "get URL" for files of any size.  That URL can be used by rsync or another client that understands HTTP retry.  That being said, Hannes or someone on Blue needs to comment on the maximum URL lifetime.  Since I think the blue box has a very short expiration.  A Get URL feature would need an expiration in, say, 24 hours rather than seconds.

**Comment by theathorn** [comment]
@briandoconnor Request from HCA Sprint Demo to provide direct file download (via curl or wget) for Pilot.

**Comment by theathorn** [comment]
Follow GDC portal model:
    - allow direct download of files from browser if total size is < 5GB. GDC creates a zipped file for download. Since we don't support that we would initially only allow direct download of a single file smaller than 5GB from the Files tab.
    - use manifest + HCA cli for individual file or file set > 5GB.

**Comment by theathorn** [comment]
Simplify to allow direct download of a single file only.

**Comment by frano-m** [comment]
Skinned - waiting for API
