### ISSUE TITLE
Project duplication in the browser

### ISSUE THREAD

**Issue by mshadbolt** [DataBiosphere/data-browser#1024]
I have noticed that some of the projects in the current data browser are duplicated.
e.g. 1.3 Million Brain Cells from E18 Mice

It is currently listing 37 projects whereas there should be 29 I believe so it seems like we have an extra 18 projects that are duplicated in some way.

**Comment by dsotirho-ucsc** [comment]
Azul team is investigating the issue.

**Comment by hannes-ucsc** [comment]
A hotfix for https://github.com/DataBiosphere/azul/issues/1488 has been deployed to `prod` and reindexing is in progress. So far only 29 projects have been detected so I am fairly certain that the fix is effective. 

I also opened https://github.com/HumanCellAtlas/data-store/issues/2641 to fix the underlying data leak in the DSS.

**Comment by NoopDog** [comment]
Fixed in prod
