### ISSUE TITLE
Add support for bulk download via 'curl' on Windows

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1354]
This works some of the time once we switched from single quotes to double quotes, but will require support for separate character escaping in Windows and a "client OS" selection in the UI.

Original title and description: Bulk download fails on Windows due to single-quoted curl command

Select "pdf" in File Format menu, Export Selected Data, and then Download Selected Data Using "curl".
The dialog then shows an un-checked "fastq.gz" option and File Format as "pdf" under Current Query.

"Request curl command" generates a single quoted command (should use double quotes) with an empty manifest.

The command errors out when pasted into a Windows command prompt.

**Comment by theathorn** [comment]
There are no pdf files with the default "Species = Homo Sapiens" facet selection.
If I de-select "Homo Sapiens" then the only remaining issue is single vs double quotes in the curl command.

**Comment by MillenniumFalconMechanic** [comment]
@hannes-ucsc, @danielsotirhos, can you confirm whether the curl command should use single or double quotes?

**Comment by dsotirho-ucsc** [comment]
> @hannes-ucsc, @danielsotirhos, can you confirm whether the curl command should use single or double quotes?

Yes, sorry about not discovering this sooner. The curl command works with single or double quotes on Mac, however only double quotes will work on Windows. So for cross compatibility it'll have to be double quotes.

**Comment by MillenniumFalconMechanic** [comment]
Got it, thanks @danielsotirhos.

**Comment by hannes-ucsc** [comment]
It looks like the escaping algorithm wasn't updated in the commit that's supposed to fix this issue. There is no point in escaping single quotes within a double quoted argument. One would need to escape double quotes. But even that wouldn't be enough: Unfortunately, Unix shells treat other characters like `$` specially between double quotes so the complexity grows. That's why I hoped we could stick with single quotes for Unix.

In Windows, single quotes aren't supported (as we just learned) and the rules for double quotes are complicated, too, but in a different way: 

https://docs.microsoft.com/en-us/cpp/cpp/main-function-command-line-args?redirectedfrom=MSDN&view=vs-2019#results-of-parsing-command-lines

I'm unsure how to move forward. For Unix there is https://www.npmjs.com/package/shlex and we should replace the current escaping algo with that. The algorithm I specified (substituting `\` with `\\` and `"` with `\'`) doesn't work either, btw. 

But I couldn't find anything for Windows. OTOH, with a regex it shouldn't be too hard to implement the rules for Windows. The biggest complexity is that stupid rule about odd number vs even number of backslashes preceding a double quote.

Either way, I think we need to abandon the desire to have one command fit all OSes. 

To those who think this is overly pedantic: be prepared for the batch download to fail because there is a quote or a dollar sign in the file name. Or when someone manages to POC a shell injection on us.

**Comment by MillenniumFalconMechanic** [comment]
Hi @hannes-ucsc, @theathorn, 

One option could be to have the user select their OS from a set of radio buttons in the Data Browser and either:

1. Reuse the existing manifest endpoint and build the OS-specific CURL commands in the Data Browser. To do this, we would need instructions/examples of CURL commands for each OS.

2. Create a new endpoint specific to generating the CURL commands, that takes an OS as a request parameter, and generates and returns a completed CURL command in the response. A separate endpoint could possibly simplify this functionality for consumers of the Azul API, including the Data Browser.

**Comment by hannes-ucsc** [comment]
As an alternative to option 2, how about returning it as part of `/fetch/manifest/files`? We would just include a command line for every OS we support. Can you reliably sniff the user's OS? IIRC, sniffing the OS has become harder in recent years due to privacy concerns.

And option 3 would be for Azul to send the URL through the URL shortener which generates URLs that require no quoting and makes the URL much shorter.

**Comment by hannes-ucsc** [comment]
Scratch option 3, there may be security concerns.

**Comment by hannes-ucsc** [comment]
@MillenniumFalconMechanic see https://github.com/DataBiosphere/azul/issues/2361 and https://github.com/DataBiosphere/azul/issues/2362. I don't think we should block this on https://github.com/DataBiosphere/azul/issues/2362. Our resolution for this should be to say "coming soon" for Windows. Once https://github.com/DataBiosphere/azul/issues/2362 is resolved, we'll need another DB ticket to integrate with the resolution for https://github.com/DataBiosphere/azul/issues/2362.

**Comment by theathorn** [comment]
Well, this ticket is to enable actual download from Windows, and as such is blocked.
The "coming soon" message can be added to #1339.

**Comment by theathorn** [comment]
No Azul tickets are blocking this work.

**Comment by NoopDog** [comment]
@theathorn This is on dev for your review.

**Comment by theathorn** [comment]
Verified download of pdf files via curl on Windows 10.
