### ISSUE TITLE
Show User Friendly Facet and Term Names from Metadata instead of machine readable names. 

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#136]
┆Issue Number: HCAB-59

**Comment by lauraclarke** [comment]
It would be great to know where this is in your priorities. I think it would be good to see this in place for MVP if at all possible 

Do let us know if it isn't clear how to get the user friendly names

cc @gabsie and @adriennes

**Comment by gabsie** [comment]
Mallory and I started entering the user-friendly names in the metadata schema.
We haven't quite finished them, but I can go through the logic and what to get with somebody from the data portal team.
cc @adriennes

**Comment by theathorn** [comment]
From @NoopDog on #hca-metadata on 9/7:
Currently the only actual display in the browser is on the tool tips over the table headings, These display the description field from the json_schema. This was hand added for now but we plan to read directly from the schema doc in the future. We are not yet using the metadata human friendly names so there are a few differences in how table columns are names (e,g. Library Construction instead of Library Construction Approach) also..  The facets and the terms also need to be modified to use the human friendly names. Currently they show what we get from bluebox which may not exactly match the current schema names.

**Comment by malloryfreeberg** [comment]
~I think this issue is done? Currently user-friendly terms are displayed in the Metadata Dictionary, not the programmatic field names.~

Oops, just realized this is in the browser repo, not the portal content repo :) disregard.

**Comment by NoopDog** [comment]
Obsolete
