### ISSUE TITLE
Modify Summary API for fileTypeSummary

### ISSUE THREAD

**Issue by frano-m** [DataBiosphere/data-browser#150]
Given the set of below it is difficult to specify the type in the json for the file type summary.
```
{
  "fileCount": 14054,
  "specimenCount": 183,
  "projectCount": 4,
  "totalFileSize": 1720374942650,
  "organCount": 6,
  "fileTypeSummary": {
    "fastq.gz": {
      "count": 14054,
      "totalSize": 1720374942650
    }
  }
}
```
Is it possible to modify the fileTypeSummary to be more like:
```
{
  "fileCount": 14054,
  "specimenCount": 183,
  "projectCount": 4,
  "totalFileSize": 1720374942650,
  "organCount": 6,
  "fileTypeSummaries": [
        {
        "fileType": "fastq.gz" 
        "count": 14054,
        "totalSize": 1720374942650
       },
       {
       "fileType": "bam" 
       "count": 14054,
       "totalSize": 1720374
       }
   ]
}
```

**Comment by theathorn** [comment]
@NoopDog requested the current format - is this no longer good? Didn't we already implement file types and sizes?

**Comment by NoopDog** [comment]
We made some hacks we can delete if the proposed structure is adopted.

I think it’s easy in the server side to change?

Thx !

------------------------------
Dave Rogers
Partner, Clever Canary
646-286-5371
http://clevercanary.com

@CleverCanary
@_DaveRogers
https://www.linkedin.com/pub/dave-rogers/0/90/92


On Jun 30, 2018, at 3:37 AM, Trevor Heathorn <notifications@github.com>
wrote:

@NoopDog <https://github.com/NoopDog> requested the current format - is
this no longer good? Didn't we already implement file types and sizes?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/HumanCellAtlas/data-browser/issues/150#issuecomment-401423531>,
or mute the thread
