### ISSUE TITLE
Swagger API for Orange Box

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#171]
Lets document the current API with the Swagger and start to plan for extensions and making the API lighter.

┆Issue Number: HCAB-161

**Comment by theathorn** [comment]
According to @hannes-ucsc this is a lot of work (since we use the Chalice microframework) and not a short term goal. @briandoconnor: we don't expect tertiary developers to be using the Orange Box APIs directly, but they may want some code examples of how to construct an index?

**Comment by NoopDog** [comment]
Ok not required.. closing.

**Comment by hannes-ucsc** [comment]
➤ Brian O&#39;Connor commented:

Ya, I think the first thing Orange will do is to provide an example indexer and frontend that other developers can learn from.  In particular the Azul indexer.  In the future it would be nice to have the API documented like ICGC so people can build directly on top of Orange (nice since they don't have to maintain anything):

https://docs.icgc.org/portal/api-endpoints/
and
https://docs.icgc.org/portal/api/

But for now I think having a functioning orange box data browser with a well-documented indexer that someone can use as the starting point for their own indexer to create a red box is a great start.

[~hannes-ucsc] what do you think, sound reasonable?

**Comment by hannes-ucsc** [comment]
This issue was moved to DataBiosphere/azul#541
