### ISSUE TITLE
Add support for project-level estimated_cell_count

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1867]
There's an estimated cell count associated with the project as well as with individual cell suspensions.
The web service will provide both values and leave it to the presentation layer (e.g. the Data Browser) as to how to present this information.
One possibility is to present the project estimated call count if it's non-zero, and otherwise use the sum of the cell suspension cell counts.

Edit: After https://github.com/databiosphere/azul/issues/3581 has been merged, implement the sorting of cell counts using the new `effectiveCellCount` sort facet.

From: https://github.com/databiosphere/azul/issues/3581#issuecomment-988116206
> This ticket leaves the sort facet `cellCount` as is and adds a new sort facet `effectiveCellCount`.
> - `cellCount`: The sum of cells from the cell suspensions
> - `effectiveCellCount`: (on proects endpoint) the larger value between the sum of cells from the cell suspensions and the cell count from the project, or (on non-projects endpoints) the sum of cells from the cell suspensions.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "The hits part is already implemented in Azul and work can progress in data browser to integrate with that. The summary part is still in the works (DataBiosphere/azul#3521)."

**Comment by NoopDog** [comment]
HI, @theathorn  We are looking at implementing this on the Data Browser. Currently, we have a "Cell Count Estimate" column that is backed by `hits[].cellSuspensions[].totalCells`. Note that `cellSuspensions[].totalCells` is aggregated in the browser by going over the list of `hits[x].cellSuspensions` in the Azul response.

This list is sortable on the UI by using `sort=cellCount` parameter in the /index/projects API call.

For the project list page, we can swap out the display of the Cell Count Estimate to use the `project.estimatedCellCount` when it is available. 
However, it seems that using`sort=cellCount` still returns items in order of the `aggregate cellSuspension[].totalCells` and is not informed by the `project.estimatedCellCount`. 

Is there a different sort key we should be using? How do you recommend we sort the projects list by the count of cells in the project?

**Comment by theathorn** [comment]
Need help from @hannes-ucsc and/or @danielsotirhos to answer the above question.

**Comment by hannes-ucsc** [comment]
The `cellCount` field is backed by the synthetic index field `estimated_cell_count` (not under `contents`) in aggregate documents. We can modify how that field is synthesized during aggregation to be `max(sum(contents.projects[*].estimated_cell_count), sum(contents.cell_suspensions[*].total_estimated_cells))` instead of just `sum(contents.cell_suspensions[*].total_estimated_cells)`. The `max` logic should NOT be applied to `cell_suspension` aggregates but I'm not sure if the synthetic `total_estimated_cells` field is even present on those aggregates.

This assumes that the DB also uses `max` to chose between `hits[i].cellSuspensions[*].totalCells` and `hits[i].project.estimatedCellCount` for the column display, obviously.

**Comment by hannes-ucsc** [comment]
Need Azul blocker, @theathorn .

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "@danielsotirhos to improve description to reflect the actual implementation. Once he's done, we'll move back to Sprint and reassign @MillenniumFalconMechanic ."
