### ISSUE TITLE
Review CGM species not rolling up issue with BE team

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1967]
When building out the “Download all project files from the project detail page” use case yesterday we came upon a behavior that I would like to bring up with the back end team.

We noticed that it seems that species is not rolled up from CGM files to the project. 

You can see in this project here

https://data.humancellatlas.org/explore/projects/53c53cd4-8127-4e12-bc7f-8fe1610a715c

The project detail page lists Homo Sapiens as the single species in this project. 

If you select the project and look at the “Donor” facet group, you will also see that “Genus Species” is shown as “Homo Sapiens”.

However, if you move over to the files tab with the project still selected,  You can see we now have two entries for Genus Species, Homo Sapiens, and Homo sapiens.

Selecting the “Homo sapiens” (lower case s) shows that these are “matrix” files with a file source of “GEO” making them CGMs.

It seems to me that the “Homo sapiens” (lower case s) should be rolled up to the project and should display on the project detail page, and the project tab’s “Genus Species” facet.

It may not be common, but it is possible for a CGM to introduce a new species, for example, in comparison with another species such as “mouse”.  When the CGM does introduce a new species it seems it would be appropriate to roll up the species to the project.

Is the CGM species, in fact not rolled up, or is this a data problem or something else?

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc "The underlying issue is that while the stratification information uses the correct `Homo sapiens`, the donor metadata in that project uses the wrong `Homo Sapiens`. Switching to ontology lookup https://github.com/DataBiosphere/azul/issues/3079 will fix this issue. It may also reveal incorrect ontology labels in the stratification information for supplementary CGMs: if both door metadata and stratification information use the wrong label, switching to ontology lookup would result in two facet terms on the Files tab, one for the correct label (as determined by ontology lookup) and one for the wrong label from stratification information. However, supplementary CGM are now deprecated and will be replaced by organically described CGMs. That is why I do not want to invest more time in the deprecated mechanism. Should switching to ontology lookup reveal inconsistencies, those can be fixed by either updating the stratification info in the project metadata or switching to the new organic mechanism for describing CGMs."

**Comment by NoopDog** [comment]
Thanks for the detailed explanation @danielsotirhos @hannes-ucsc.

**Comment by NoopDog** [comment]
Reading the above text it appears that while the new deprecated "supplementary CGMs" do not roll up species to the project, the newer "organic mechanism for describing CGMs" does.

This satisfies the main question of this ticket. Going forward, the species of newly added CGMs will be expected to roll up to the project as they will be described organically.

While this specific issue will be fixed by Azul  DataBiosphere/azul#3079 it seems it would be desirable at some point to update all supplementary CGM with organically described CGMs.
