### ISSUE TITLE
Create a fake matrixable bundle and get it indexed in DSS integration environment

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#256]
┆Issue Number: HCAB-229

**Comment by hannes-ucsc** [comment]
I was asked to check bundle `21454ad9-8e5a-48a8-b2e6-bb4dcf125c5b`. Yes, it shows up in the index as contributing a matrix file. Unfortunately, so do eight other bundles. I'm assuming these are results of previously failed attempts?

```
      "bundles": [
        {
          "bundleUuid": "caf0942c-61f1-4923-8e2c-ada0838b3304",
          "bundleVersion": "2018-10-05T220632.668313Z"
        },
        {
          "bundleUuid": "1326e6ed-2a1c-4009-95b5-8458c82e24f4",
          "bundleVersion": "2018-10-01T205623.983943Z"
        },
        {
          "bundleUuid": "2e6406dd-de7b-4e73-a942-7ce2f6b3061a",
          "bundleVersion": "2018-10-02T223555.796779Z"
        },
        {
          "bundleUuid": "21454ad9-8e5a-48a8-b2e6-bb4dcf125c5b",  # this one should stay
          "bundleVersion": "2018-10-02T213109.504549Z"
        },
        {
          "bundleUuid": "8e60fe1f-2217-4a15-9c2f-4e79cc341196",
          "bundleVersion": "2018-10-01T204932.824613Z"
        },
        {
          "bundleUuid": "f0a2cbce-b932-4700-9032-2e99516e6caa",
          "bundleVersion": "2018-10-01T205831.108803Z"
        },
        {
          "bundleUuid": "b5edd2e7-d588-4dda-b1cb-409d9d32a97e",
          "bundleVersion": "2018-10-01T212259.949775Z"
        },
        {
          "bundleUuid": "72174501-a888-4a86-8555-8c6e8d16b3f0",
          "bundleVersion": "2018-10-01T205150.992179Z"
        },
        {
          "bundleUuid": "fd6b9d57-1f5a-481d-bd75-f2702dc5b610",
          "bundleVersion": "2018-10-01T211755.665408Z"
        }
      ]
```

There are also two other `matrix` files. The bundles they occur in should also be deleted:

A file named `d20fb2dd-3d98-4516-a648-dee5e1917bd7.matrix` with

```
      "bundles": [
        {
          "bundleUuid": "7d391c1f-6cfb-4d37-b52e-0bdc14c64310",
          "bundleVersion": "2018-09-28T000343.352657Z"
        }
      ]
```

and another file also named `d20fb2dd-3d98-4516-a648-dee5e1917bd7.matrix` with 

```
      "bundles": [
        {
          "bundleUuid": "00074676-e374-453e-9284-9a12ac03fe18",
          "bundleVersion": "2018-09-28T003320.132505Z"
        }
      ],
```

All bundles listed here, with the exception of `21454ad9-8e5a-48a8-b2e6-bb4dcf125c5b` should be deleted by the person that uploaded them because only they can authoritatively decide if and which of those bundles should be deleted. I'm assuming this is @mckinsel. 

Note: The above information was extracted from the Azul service response for `integration`:

https://service.integration.explore.data.humancellatlas.org/repository/files?size=15&filters={"file":{"fileFormat":{"is":["matrix"]}}}

**Comment by theathorn** [comment]
@mckinsel What's the status on this?

**Comment by mckinsel** [comment]
We talked about it on slack. I think @hannes-ucsc is filtering by date to avoid the other test bundles.

**Comment by theathorn** [comment]
Workaround in place.
