### ISSUE TITLE
Add "Normal" label to non-diseased data in data browser

### ISSUE THREAD

**Issue by adriennes** [DataBiosphere/data-browser#274]
Non-diseased data should be marked "Normal" in the data browser table, rather than blank

- - -
**Mallory comments:**

To summarize the discussion in the thread below:

* [x] List the disease value if there is one. It will be a disease (or multiple) or "normal".
* [x] If there is no value, list "Unspecified".
* [x] Do the same thing in the list and the facets.
* [x] Change "Diseased" to "Known diseases" in the facets and column headers

┆Issue Number: HCAB-242

**Comment by malloryfreeberg** [comment]
I think instead of entering "normal", a phrase like "not provided" should be used. If the field is blank in the metadata, we actually don't know whether the data are from disease or non-disease donors or tissues/specimens. This field isn't required in the metadata so it's possible contributors just didn't provide it for whatever reason. I would not feel comfortable claiming a donor or tissue/specimen is "normal" when we actually don't know.

Happy to hear suggestions for other terms than "not provided".

**Comment by NoopDog** [comment]
We have used "Unspecified" in the facets to indicate the value was not specified vs specified as "unknown".

<img width="549" alt="screen shot 2018-10-25 at 8 30 49 pm" src="https://user-images.githubusercontent.com/3239697/47494470-0c20c100-d895-11e8-8a01-21299f5161b3.png">

So perhaps we can stick with "Unspecified" or change it uniformly.

@malloryfreeberg is the data ever tagged as "normal"?  Is there even such a thing or is all you can say definitely is the presence of some disease and not the absence of all other diseases?

**Comment by malloryfreeberg** [comment]
> So perhaps we can stick with "Unspecified" or change it uniformly.

"Unspecified" is a reasonable choice.

> is the data ever tagged as "normal"? Is there even such a thing or is all you can say definitely is the presence of some disease and not the absence of all other diseases?

These are great questions! Yes and yes. For the two disease fields in the metadata, a contributor can indicate that there are "*no known diseases*" for their donor or specimen by entering "normal" for the field. The "normal" term is governed by the ontology term [PATO:0000461](http://ontology.staging.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000461). The metadata team has crafted the definition of the `diseases` field to be:

"Short description of known disease(s) of the organism. Enter 'normal' if no known disease."
and
"Short description of known disease(s) of the specimen. Enter normal if no known disease."

Since this field is not required, there will be many instance of not having it in the metadata. Using "unspecified" in this instance would be reasonable.

**Comment by NoopDog** [comment]
Ok great so in summary:

1. List the disease value if there is one. It will be a disease (or multiple) or "normal".
1. If there is no value, list "Unspecified".
1. Do the same thing in the list and the facets.

Is that about it?

**Comment by malloryfreeberg** [comment]
Sounds great!

I might also suggest:

4. Change "Diseased" to "Known diseases" as the column header.

I could also make another ticket for that, if it's more helpful.

**Comment by NoopDog** [comment]
I think we can keep working here...

Shall we change the name of the facet as well then? Would like to keep the facet names and the table columns matching as best as possible to make it easier for the user to map between them.

**Comment by NoopDog** [comment]
If we can summarize in the top section here with 

- [ ] these things

**Comment by malloryfreeberg** [comment]
Yes, please change it wherever it's used. The main point is to emphasize that these are the "known" things, but that there might be currently unknown things discovered post-analysis.

**Comment by zperova** [comment]
@frano-m I would like to add that we have Known diseases for the organism and Known diseases for the specimen. The browser should display Known diseases for the specimen as the specimen might come from a tissue that is not affected by the organism's disease. Currently, I can see both specimen and organism diseases in the Browser.

**Comment by NoopDog** [comment]
Hi @malloryfreeberg these updates have been promoted to staging. Would love to have your feedback.

 https://staging.data.humancellatlas.org/explore/projects

Thanks,
D

**Comment by malloryfreeberg** [comment]
The points in this ticket are addressed, thanks!

I have made an additional related issue #335 .
