### ISSUE TITLE
Show exact number when hovering over rounded number with metric suffix

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#289]
Counts are displayed using a metric suffix. For example, `5088` is displayed as `5.1K`. This is useful but often users will want to know the exact number. I personally need that right now to verify the file counts in staging against the CBeta spreadsheet. 

I propose that we display the exact number as a title-style popup when the user hovers over such a rounded number.

┆Issue Number: HCAB-255

**Comment by NoopDog** [comment]
Yup Sounds good. Thx

**Comment by malloryfreeberg** [comment]
@hannes-ucsc @NoopDog I would argue that the exact count for files and cells would be preferred over the summary count as the default. I didn't realize I could get the exact count by hovering until Dave told me. This doesn't seem intuitive to me.

I would agree that File Size can be kept in TB, GB, etc. since that's how people generall think of file sizes. I don't see any reason why the File count should be summarized, though. I also don't know what File count is counting, exactly. Primary fastq files? Also secondary files? What happens when we start to have imaging files? 

Cell count is a bit trickier to know what to do with given that the counts are estimates anyway and many projects are missing cell counts. Therefore, the cell count is actually an underestimation.
