### ISSUE TITLE
Organoid project doesn't display correct organ

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#302]
The 10x demo dataset (project) - human cerebral organoids - displays the Organ as "skin of body". This is not accurate in the context of what the data represent. 

In this project, skin samples were taken from donors, the skin cells in the sample transformed to become pluripotent (induced pluripotent stem (iPS) cells, or cells capable of becoming another cell type), differentiated into organoids that represent the brain (i.e. cerebral organoids), and then cells taken from the cerebral organoids were then sequenced. 

donor -> skin sample (specimen) ~~> iPS cells (cell line)~~ > brain organoid (organoid) ~~> neural cells (cell suspension)~~ > sequencing files

So, the dataset _actually_ represents the Organ brain (represented in the metadata in the `organoid.model_for_organ.text` field). 

Having the Organ for this project be "skin of body" - the sample taken directly from the donor before being converted to iPS cells and then cerebral organoids - is misleading.

![screen shot 2018-10-26 at 13 51 58](https://user-images.githubusercontent.com/10993501/47567411-5c942f00-d926-11e8-969d-83ea0b39fd21.png)

┆Issue Number: HCAB-265

**Comment by hannes-ucsc** [comment]
@malloryfreeberg can you help us specify an algorithm—that works for all bundles across all projects— for extracting the correct organ and organ part information from the graph of metadata entities? The algorithm should define  direction and order of graph traversal as well as which field to consider from every entity. Something like: 

1) Start from a specimen_from_ and go upwards in the graph.
2) When you encounter an organoid, extract field x and y if present and exit, otherwise continue
3) If you encounter an specimen_from_organism, extract fields a and b and exit, …

**Comment by malloryfreeberg** [comment]
@hannes-ucsc sure thing! I'll work on this and review with the other wranglers.

**Comment by malloryfreeberg** [comment]
@hannes-ucsc I've spoken with @zperova and this is what we came up with.

### Proposed algorithm
1. Start from `sequencing_file` (or `imaging_file`) and go upwards in the graph.
1. If you encounter `organoid`
    1. Extract `organoid.model_for_organ.text` and `organoid.model_organ_part.text` fields, if present
    1. Exit algorithm
1. If you don't encounter `organoid`, continue until you encounter `specimen_from_organism`
    1. Extract `specimen_from_organism.organ.text` and `specimen_from_organism.organ_part.text` fields, if present
    1. Exit algorithm
1. If you don’t encounter `specimen_from_organism`:
    1. Fail gracefully (maybe set `organ` to "Unspecified")
    1. Contact a wrangler
    1. Exit algorithm

### Notes
- If `organoid` is encountered, it supersedes any `specimen_from_organism`.
- We don't actually have any imaging data files yet, but the general approach *should* be the same.
- `*.text` are the free text fields used now. Should be replaced with `*.ontology_label` in the future.
- `organoid.model_for_organ` ≍ `specimen_from_organism.organ`
- `organoid.model_organ_part` ≍ `specimen_from_organism.organ_part`

**Comment by hannes-ucsc** [comment]
Is `organoid` invariably downstream from `specimen_from_organism`? And is `cell_suspension` invariably downstream from `organoid`? I think it's yes on both, just want to make sure.

**Comment by zperova** [comment]
@hannes-ucsc yes, organoid is downstream of 'specimen_from organism' and 'cell_suspension' is downstream of 'organoid' (if there is one), if not it is always downstream from "specimen_from_organism".

**Comment by mckinsel** [comment]
@malloryfreeberg @zperova , I think this might break for "Single-cell RNA-seq analysis throughout a 125-day differentiation protocol that converted H1 human embryonic stem cells to a variety of ventrally-derived cell types.". I'm pretty sure those get marked as "blastocyst" from this algorithm, but they are not blastocysts.

**Comment by malloryfreeberg** [comment]
Great point @mckinsel . We were all just discussing this the other day (@zperova @hewgreen ) and decided that we were missing the modelling of the actual differentiated cell line. I believe Matt is adding this in prior to re-ingestion, and is indicating the `cell_type` as "interneurons" and the `model_organ` and "brain". The model would then go:

... -> H1 stem cell line -> differentiated interneuron cell line (organ: brain) -> cell suspension -> sequence file

Cell lines would be treated like organoids. If you encounter them first travelling up from the sequence file, extract the organ information from the cell line rather than any upstream specimens.

**Comment by zperova** [comment]
@mckinsel you are right. The algorithm needs to be updated to incorporate the new field cell_line.model_organ.ontology_label in case of cell lines.

**Comment by hannes-ucsc** [comment]
@malloryfreeberg 

This issue is about the project "HPSI human cerebral organoids" which now shows "brain" instead of "skin". I am under the impression that this is the desired behavior and will be closing this ticket. If that is not correct, please reopen.

The above comments indicate that there is another [project](https://prod.data.humancellatlas.org/explore/projects/f8880be0-210c-4aa3-9348-f5a423e07421) where the Data Browser still displays the wrong organ. @mckinsel [alludes](https://github.com/mckinsel) that this project currently displays "blastocysts" which it doesn't. It displays organ "embryo". What organ should be displayed? If would help if this information (which project, current behavior, expected behavior) were captured in a new issue, unless there already is one. #338 sounds similar. I think I understand what the fix is (including cell_line.model_organ and preferring a downstream `cell_line` over upstream, "sample-like" biomaterials like `organoid` or `specimen` in the graph.
