### ISSUE TITLE
Request buttons for manifests at the level of all Projects page (Checkbox Problem)

### ISSUE THREAD

**Issue by gabsie** [DataBiosphere/data-browser#314]
Hello, 

I am not sure about what is the expected activity here with the two Requests buttons available on the Projects page: https://staging.data.humancellatlas.org/explore/projects , and what scenario we are supporting for users. 
I am thinking this is not entirely finished, maybe, so I'm sorry if I'm reporting anything known.

1. If the desired scenario is:
"I want to download the data for this project", then there should be an option for me to select just that project, and then have an opportunity to request the files for it, raw or matrix.

At the moment both buttons speak about selections, but there are no options to select one or several projects.

1. Should it be possible to go and download all files for all projects?
I think I just requested this manifest with everything, but it got me to an Internal error page. Not sure what is expected to happen. 

From an error prevention principle point of view, whatever is going to cause an error shouldn't be made possible/clickable, and should instead give notification or instructions on what to do. At the moment the buttons allow me to click them when both popups open.

![screen shot 2018-10-26 at 18 37 33](https://user-images.githubusercontent.com/19713125/47583972-d17c5e80-d950-11e8-9ce2-41b978898815.png)

![screen shot 2018-10-26 at 18 44 59](https://user-images.githubusercontent.com/19713125/47583961-c9242380-d950-11e8-95bc-d24edcf2a931.png)

![screen shot 2018-10-26 at 18 57 05](https://user-images.githubusercontent.com/19713125/47584041-fa9cef00-d950-11e8-900b-be7f2c8a321a.png)

┆Issue Number: HCAB-277

**Comment by NoopDog** [comment]
HI @gabsie let me try to address:

### Downloading Data for a Project 
Currently, to select a project the user must use the project facet under "More"
![Screen Shot 2018-11-20 at 11.20.48 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/c69d73b5-87a9-475f-972b-c9ffbaf59ec2

Once a project facet is selected, they can continue to select other facets, add additional projects or request the download. We are working on making it easier to select a single project but currently the project facet is how this use case is supported.

The link on the projects table for the project, implements "View Project Detail". This does not select the project as a facet. 

### Manifest or Matrix for ALL data.
It is still being worked out if we want to allow "Downloading Everything". We need to define what limits we might put on the requests for manifests and matrix files. So for now, it is possible to ask for "everything". Also, there are currently some scaling issues (that are also being addressed ) that prevent "download all" or "manifest for all from completing properly.

Yes, we understand that users should not be offered todo actions that will fail and we are working on 1) Refining the requirements of what is an acceptable request 2) Scaling to handle the larger requests. 

### Request buttons for manifests at the level of all Projects page
The projects tab is a list of projects that match the selected facets so if someone selects Organ:Liver they would only see projects that have data about an organ that is a liver.  Same goes for the "Specimens" and "Files". The facets apply to all tabs equally. The manifest contains links to all files that match the selection criteria. A user gets the same manifest regardless of what tab they are on.

I think what might be confusing here is that the download buttons are underneath rather than above the tabs making the hierarchy unclear. This is also on our roadmap to adjust as we refine how we educate the user about what facets are available and indicate how to find and select them. 


Let me know if this answers your questions or you would like to discuss. 
Cheers,
Dave

**Comment by theathorn** [comment]
Obsolete DCP/1 issue.
