### ISSUE TITLE
Neuron_diff Project doesn't display correct organ.

### ISSUE THREAD

**Issue by zperova** [DataBiosphere/data-browser#338]
The SS2 demo dataset (neuron_diff project) displays the Organ as "embryo". This is not accurate in the context of what the data represent.

This issue is related to the https://github.com/HumanCellAtlas/data-browser/issues/302

However, this issue is currently blocked as there is no representation of a modelled organ in our current metadata schema for the cases of cell types differentiated from embryonic stem cells. In this particular case the `organ` that comes from the `donor` (what we capture and what is used to display in the browser) is not the organ that is modelled by the cell line.

Once we resolve it within our repo, we will be able to provide an algorithm to resolve such cases.

┆Issue Number: HCAB-298

**Comment by malloryfreeberg** [comment]
Can be addressed similarly to organoids in #302. 

See Marcus' [comment](https://github.com/HumanCellAtlas/data-browser/issues/302#issuecomment-479207581)

**Comment by theathorn** [comment]
Probably need an azul ticket for this.

**Comment by hannes-ucsc** [comment]
What is the expected organ?

**Comment by zperova** [comment]
@hannes-ucsc The expected organ for this dataset is `brain`

we now introduced a new field for datasets using cell lines "model_organ" This should be used to show organ for the datasets using cell lines, specifically the algorithm here would be:
start with  the sequence_file (or image_file):
sequence (image) file -> cell suspension -> cell line:  if encounter "cell_line" extract from `cell_line.model_organ.text` (I believe further on we have agreed to extract from `cell_line.model_organ.ontology_label` instead but not sure when this will be implemented)

if there is no cell_line continue to specimen_from_organism and extract from specimen_from_organism.organ.text or specimen_from_organism.organ_part.text

**Comment by hannes-ucsc** [comment]
So https://github.com/HumanCellAtlas/metadata-api/issues/51 will introduce support for a cell line's model organ, and https://github.com/DataBiosphere/azul/issues/930 will incorporate that field into Azul's index. 

The organ display in the Projects tab of the browser is backed by `hits[*].projectSummary.organSummaries` which is in turn, backed by `contents.cell_suspension` in contributions which is built by doing a secondary graph traversal starting at the cell line. I'd rather avoid the need for that secondary traversal but I have no idea how. If we leave the secondary traversal in place, we need to incorporate the rule @zperova described above.

@NoopDog I think DB should stop populating the organ column on the Projects tab from `hits[*].projectSummary.organSummaries` because it will cause problems with imaging bundles which don't have `cell_suspension` instances but `imaged_specimens` instead. Because they lack cell suspensions, organSummaries will not mention any organs associated imaged specimens.  Instead DB should populate that column from `hits[*].(cellSuspensions|organoids|`~imagedSpecimens|~`specimens).(modelOrgan|organ)`.

**Comment by hannes-ucsc** [comment]
… or alternatively from `hits[*].samples.(modelOrgan|organ)`, if only the sample organ is desired.

**Comment by zperova** [comment]
@hannes-ucsc what do you mean by `samples`? we don't have `samples` in our metadata.

**Comment by NoopDog** [comment]
Hi @zperova @malloryfreeberg @adriennes 

The specimens tab is being rolled up into a "samples" tab where the sample is the first biomaterial above the cell suspension.  We have a "Sample Type" column on the samples table that indicates if the biomaterial is a specimen, cell line or organoid.

You can see this nearing completion on:
https://dev.data.humancellatlas.org/explore/samples

We have the option of displaying either the organ, model organ or both depending on what makes sense.

specimen has an "organ" field
organoid has only a "model organ" field
cell line has both an "organ" and "model organ" field.

We have the sample and we have also knowledge of specimens and their organs if they exist. For example we might have one sample "skin of body" that was used to create an organoid with model organ brain. In this case the sample would be the organoid, and we would also be able to see the specimens that are in the project and could have been used to create an organoid.

## Organ
Organ we can take from either the specimen organ field or the sample cell line's organ field if it exists. - What to do if there is "organ" on both a cell line in the project and there is a specimen.organ? Prefer one or show both?

## Model Organ
This will come from the cell line or organoid.model_organ or cell_line.model_organ if they exist from the sample (first biomaterial above the cell suspension) 

## Column Header

For the column header I think we can change this to  "Organ/Model Organ".

## Column Value

We have a few cases we need to cover where the data has

1. Only organ
1. Organ and model organ
1. Only model organ

### Some Display Options

1)  Prefer Model Organ if it exists otherwise use Organ
- If the project has a cell line or organoid that has a model organ, then display that only in the Organ/Organ model field. If the project has only specimens, then use the specimen organ set. The field right next to "organ" is the "sample type" so it might  be obvious from context if the value is an organ or model organ. e.g.
```
cell line | brain
specimen  | kidney 
```

2) Multiple Values
- Display any organ list followed by "/" then model organ e.g

```
organoid  | skin of body / brain
sample    | kidney
cell line | unspecified / heart
```

3) Single Value but prefer specimen organ if it exists 

```
organoid  | skin of body
sample    | kidney
cell line | heart
```

We have the exact same opportunity with organ part/model organ part.

Would appreciate your ideas on how to present this.

**Comment by zperova** [comment]
@NoopDog @malloryfreeberg @adriennes 

I think we should replace the "specimen" to "primary tissue"  in the Sample Type column - this makes more sense as "specimen" is very general and can mean both "cell line" and "organoid".

I would have one column called "Organ/Organ model":
For primary tissue (currently specimen) I would display organ_parts if specified, otherwise display organ - if this substitution within the field is not desirable, I would display organ (since organ_parts are likely to be unspecified in the majority of cases).

For cell line I would display model_organ (because organ is likely to be unspecified) - there are some use cases that won't be covered if we do this, I am happy to discuss.

For organoid I would display model_organ as well.

**Comment by malloryfreeberg** [comment]
Regarding "primary tissue" instead of "specimen from organism", there has been some [recent chatter on an older metadata ticket](https://github.com/HumanCellAtlas/metadata-schema/issues/389#issuecomment-476280201) about renaming `specimen_from_organism`, which might work nicely to deal with the slight confusion that "specimen" causes.

**Comment by NoopDog** [comment]
Ok this looks great. We can start with this. I think given the timeline we will go first with "specimen" and then change to "primary tissue" when the metadata change comes through.  

Currently Organ and Organ Part are separate columns. 
Based on your notes above we can:

1) Rename Organ column to "Organ/Model Organ"
2) Rename Organ Part to "Organ Part/Model Organ Part"
3) Show specimen.organ in the "Organ/Model Organ" column  if the sample is a specimen.
4) Show cellLine|organoid.model_organ in the "Organ/Model Organ" column if the sample is a cell_line or organoid.
5) keep the term "specimen" for now until the ontology changes.

@hannes-ucsc Looks like we can do this mapping above in the client from the api response. 
@zperova @malloryfreeberg   any comments or concerns?

**Comment by hannes-ucsc** [comment]
Re "primary tissue": Blood isn't a tissue but is used as a specimen.

@NoopDog I think the logic you propose is unnecessarily complicated. On the Samples tab, you can get the same effect simply by displaying `hits[*].samples[0].organ` and `hits[*].samples[0].modelOrgan` in the `Organ/Model Organ` column. Only one can be set. You may be able to correlate `hits[*].samples` with `hits[*].(specimens|organoids|cellLines)` on the samples tab but on other tabs, that won't work. However, `hits[*].samples[0].organ + hits[*].sample[0].modelOrgan` should work on all tabs.

I proposed this ad nauseam: I would prefer if the UI didn't select organ over modelOrgan or vice versa but always displayed both, either in one column—with the values annotated as either O and MO—or in two separate columns. That way it is always clear which is which, but no preference in the UI of one value over the other.

**Comment by NoopDog** [comment]
Ok then, looks like we are proposing basically the same thing @hannes-ucsc. Please see https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-browser/586

I will make this ticket depend on #586.

**Comment by theathorn** [comment]
@zperova This should be fixed in prod - can you verify?

**Comment by zperova** [comment]
@theathorn yes, I can verify that with the current design, this issue is fixed in prod. Closing the ticket.
