### ISSUE TITLE
Direct download UX is inconsistent with native downloads

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#354]
The XHR with `responseType="blob"` method that we are currently using for direct downloads appears to read the entire response into memory before the browser's native download dialog appears. There is no progress information during the download (except in the network tab of Chrome's inspect UI).

Because the UX is inconsistent with how downloads work natively in web browsers, I fear that many users will be tempted to assume that the download has stalled, especially for files that take minutes to download, like multi-gigabyte BAMs.

It might also be problematic that these large files are buffered in memory (I read that on SO) but we'd have to verify that this is true, and on what platforms.

┆Issue Number: HCAB-308

**Comment by hannes-ucsc** [comment]
I think the way to fix this is to modify the proxy endpoint that I recently added to Azul. It currently returns a 302 redirect to the file in the checkout bucket. It should instead return a 200 response with JSON payload that contains the URL. Then the data-browser can change the XHR from `responseType="blob"` back to JSON, extract the final file URL and issue another request, using window.open() or by invoking `.click()` on a hidden A element. My JS knowledge is from 2012 so take the last bit with a grain of salt. Anyhow, not using XHR for the final request should launch the browser's native download machinery.

**Comment by theathorn** [comment]
@NoopDog Assigned to Mim for now but feel free to re-assign as appropriate.

**Comment by hannes-ucsc** [comment]
@NoopDog, @MillenniumFalconMechanic let me know if you want to go the proposed route. I will then open the upstream ticket in Azul.

**Comment by NoopDog** [comment]
Hi @hannes-ucsc yes what you are suggesting is how the original download UI mocks worked. We had to move away from that because of the redirect flow for the demo but now that we all have time to work on this, yes lets move towards the original intent. 

If you give us the url in json instead of doing the last redirect, we can give the user the option to download or just copy the URL to curl.

Can you paste in a snippet of what the returned JSON will look like?

Thanks,
Dave

**Comment by hannes-ucsc** [comment]
> If you give us the url in json instead of doing the last redirect, we can give the user the option to download or just copy the URL to curl.

Don't know if I like that option but not my call. It's an additional click that might confuse users. @adriennes?

> Can you paste in a snippet of what the returned JSON will look like?

```
{
    "location": "https://dss-checkout-staging.s3.amazonaws.com/blobs/…"
}
```

I used `location` because that's consistent with the name of the HTTP header. But that is only of aesthetic significance.

**Comment by hannes-ucsc** [comment]
Just a heads up: The response might change to what's described here:

https://github.com/DataBiosphere/azul/issues/546#issuecomment-438908724

**Comment by theathorn** [comment]
@MillenniumFalconMechanic databiosphere/azul#551 is done (deployed to dev by @hannes-ucsc ) so you should be able to proceed with this ticket.

**Comment by NoopDog** [comment]
@hannes-ucsc @theathorn the fix for this is deployed to ux-dev

 https://ux-dev.data.humancellatlas.org/explore/projects

This points to   https://service.dev.explore.data.humancellatlas.org.

The next step is for the download bucket to be configured to set the Content-Disposition header to "Attachment" instead of "in-line" or not set. 

Is that a blue box thing? Who can set this for us and make sure it gets into their terraform scripts?

Currently you will see that pdf and txt open in a new browser window instead of downloading, The other file types download. I think this will be fixed once the content-disposition is set to attachment.

![Screen Shot 2019-01-11 at 9.28.28 PM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/d6bc767a-26d5-4fa8-8c2d-f6f583dec312)

**Comment by NoopDog** [comment]
@hannes-ucsc We have one more update pushed to UX dev and should now work if the file is not already in the checkout bucket. PDF, txt etc still open instead of download however so content-disposition still needs to be set.  I was able to get a txt file to download by changing content-disposition to attachment as described above.  However it downloads with the wring name so look like the `filename` needs to be set as well as part of the content-disposition header.
