### ISSUE TITLE
Request Expression Matrix button incorrectly enabled

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#403]
In prod, select "File Format = mtx" and 2 projects are shown with the "Request Expression Matrix" button enabled even though the "Matrix" column has zero counts for both projects.
Performing a "Select Project" for either one disables the matrix button, but if both are listed then the button **is** enabled.

┆Issue Number: HCAB-337

**Comment by MillenniumFalconMechanic** [comment]
@theathorn  @hannes-ucsc 

When `mtx` is selected in the file format facet, the [backend API](https://service.explore.data.humancellatlas.org/repository/projects?filters=%7B%22file%22%3A%7B%22fileFormat%22%3A%7B%22is%22%3A%5B%22mtx%22%5D%7D%7D%7D&size=15&sort=specimenId&order=desc) returns a matrix count of 2 in the `termFacets` and a matrix count of 0 in the `hits` values of the response object.

`termFacets` populates the facet drop drowns. `hits` populates the table column values.

We would expect the matrix value in both `termFacets` and `hits` to match, and in this case, be either 2 or not specified at all.

Response object:

```
{
  "hits": [
    {
      ...
      "fileTypeSummaries": [
        {
          "fileType": "fastq.gz",
          "count": 28,
          "totalSize": 106207103028
        },
        {
          "fileType": "tsv",
          "count": 56,
          "totalSize": 222009103
        },
        {
          "fileType": "mtx",
          "count": 28,
          "totalSize": 2513088649
        },
        {
          "fileType": "h5",
          "count": 42,
          "totalSize": 2830488402
        },
        {
          "fileType": "csv",
          "count": 14,
          "totalSize": 9125
        },
        {
          "fileType": "bam",
          "count": 14,
          "totalSize": 124871709783
        },
        {
          "fileType": "bai",
          "count": 14,
          "totalSize": 68576568
        },
        {
          "fileType": "unknown",
          "count": 14,
          "totalSize": 37345879
        }
      ]
  ],
  "termFacets": {
    ...
    "fileFormat": {
      "terms": [
        {
          "term": "fastq.gz",
          "count": 11
        },
        {
          "term": "bai",
          "count": 4
        },
        {
          "term": "bam",
          "count": 4
        },
        {
          "term": "csv",
          "count": 4
        },
        {
          "term": "pdf",
          "count": 3
        },
        {
          "term": "h5",
          "count": 2
        },
        {
          "term": "matrix",
          "count": 2
        },
        {
          "term": "mtx",
          "count": 2
        },
        {
          "term": "results",
          "count": 2
        },
        {
          "term": "tsv",
          "count": 2
        },
        {
          "term": "txt",
          "count": 2
        },
        {
          "term": "unknown",
          "count": 2
        },
        {
          "term": "fastq",
          "count": 1
        }
      ],
      "total": 12,
      "type": "terms"
    }
  }
}
```


See attached screenshot:

![Screen Shot 2018-12-14 at 11.03.38 AM.png](https://images.zenhubusercontent.com/57339587bf93871ccd9ae22c/93073a38-101a-43af-bd12-61b67f3151c3)

**Comment by hannes-ucsc** [comment]
Responding here because it has more meat that the corresponding Azul ticket.

I'm confused by the request for both numbers to match. In a `/repository/projects` response, each hit represents a project. The`hits[*].fileTypeSummaries[*].count` properties describe the number of **files** of a given type in a project. The example `hits` portion in the above comment lists one hit. That hit represents one project. The hit has no `fileTypeSummaries` item with a `fileType` of `matrix`. That indicates that there are no matrix (`.zattrs`) files in that project. There is an entry for `mtx` with a `count` of `2` indicating that there are two `.mtx` files in that project.

Each of the `termFacets.fileFormat.terms[*].count` properties of a `/repository/projects` response describes the number of **projects** that have files of a particular type, not the number of files of that type. In the above example this means that there are two projects with `matrix` (`.zattrs`) files and two projects with `mtx` files.

There is one twist: terms of the same facet are conjunctive, terms of different facets are disjunctive. So even if you select `mtx` in the file type facet drop down, the `matrix` facet entry doesn't disappear or change its count, even if neither of the two projects with `mtx` files contain `matrix` files. There are two **other** projects that have matrix files.

If all this is familiar, and I'm just misunderstanding what this ticket is about, let me know.

**Comment by NoopDog** [comment]
@theathorn the fix for this is deployed to prod. Can you validate and close? Thanks.
