### ISSUE TITLE
[HCA DX] Track clicks on export request buttons

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#4191]
### Need
We need to track clicks on export buttons such as "Request Link" for export to Terra, and "Prepare Manifest" for file manifest.

### Approach
~~Investigate reuse of curl download event.~~ See comments below for approach.

### Needs
- [x] Merge [Findable PR](https://github.com/DataBiosphere/findable-ui/pull/224)
- [x] Create a findable version - 14.0.0 https://github.com/DataBiosphere/findable-ui/pull/244
- [x] Update data-browser to new findable version -14.0.0 (#4235)
- [x] Deploy data-browser with new findable version (#4247)
- [x] Create GTM tags

#### curl Command
- [x] data.humancellatlas.org - GA4
- [x] data.humancellatlas.dev.clevercanary.com - GA4

#### File Manifest
- [x] data.humancellatlas.org - GA4
- [x] data.humancellatlas.dev.clevercanary.com - GA4

#### Export to Terra
- [x] data.humancellatlas.org - GA4
- [x] data.humancellatlas.dev.clevercanary.com - GA4

**Comment by mrtopsyt** [comment]
Hi @MillenniumFalconMechanic! I took a look through the existing `bulk_download_requested` event, and I think it could be reused, but I found several issues that would need to be considered:

- A new parameter for `export_type` would need to be added, containing info about the tool being used (e.g. `curl_command`, `terra`, etc.) 
- The `current_query` parameter contains the full JSON query, but frequently gets cut off due to GA4's [character limits](https://support.google.com/analytics/answer/9267744?hl=en). This could be addressed by instead passing a parameter containing only the options selected on the export form (e.g. file format, species) and extracting the selected filter from the `fullPageUrl` dimension, which is collected by default and has a much higher character limit, since the filter is included in the URL.
- The existing event would not be useful for backpage exports, since the event does not contain any info about the ID of the selected project/workspace but does include info about the entity the export is being made from in the `index` field. It would probably make sense to create a new event to track backpage exports
- The existing parameter for `index` could be renamed to `entity_name`, to match other events
- The `tool_name` parameter, which has a value of either `bash` or `cmd.exe`, only makes sense for Curl downloads. It could be deprecated or passed a null value for other tools
- The `catalog` parameter may not be useful since events are already tracked separately for different sites, and it may be worth deprecating.

Let me know if you what you think about this, and I can make a findable ticket to add these changes and call the event on other existing events

**Comment by MillenniumFalconMechanic** [comment]
* Model exports separately (e.g. `build_download_requested`, `file_manifest_requested`).
* Use page URL rather than `current_query`.
* Back pages will have a separate event.
* No custom params/dimensions for Species, File Type, Download Format etc.
* Remove `catalog` param.
* Make `tool_name` optional?
* Update `index` to `entity_name`.

**Comment by MillenniumFalconMechanic** [comment]
Hi @jpaten, the [corresponding PR](https://github.com/DataBiosphere/data-browser/pull/4201) has been merged and deployed to dev.

**Comment by mrtopsyt** [comment]
Thanks @MillenniumFalconMechanic!

**Comment by jpaten** [comment]
@MillenniumFalconMechanic Would you be able to review GTM version [57](https://tagmanager.google.com/#/versions/accounts/4492049679/containers/10468455/versions?containerDraftId=72) for this one?

**Comment by mrtopsyt** [comment]
@MillenniumFalconMechanic I'm so sorry, I realized I mistagged the corresponding PR  #4201 , which should have been associated with #4181! This shouldn't require any action though, because this ticket does not require any code changes to the data-browser repo. The only code changes are in https://github.com/DataBiosphere/findable-ui/pull/224. Once that's reviewed, I'll go ahead and create a GTM version for this ticket, and comment it here. So sorry again for the confusion!

**Comment by MillenniumFalconMechanic** [comment]
Hi @jpaten, Findable 14.0.0 has been deployed to dev. Can you continue with the configuration and testing against dev while we wait for the prod deploy?

**Comment by mrtopsyt** [comment]
Hi @MillenniumFalconMechanic! Yep, I can do that

**Comment by mrtopsyt** [comment]
Version [#62](https://tagmanager.google.com/#/versions/accounts/4492049679/containers/10468455/versions) on GTM

**Comment by MillenniumFalconMechanic** [comment]
#62 LGTM, thanks @jpaten!

**Comment by mrtopsyt** [comment]
Working on staging and prod @MillenniumFalconMechanic!

Prod
![Image](https://github.com/user-attachments/assets/264b6e06-a1d0-4f20-a3e3-ac7d69d0d45b)

Staging
![Image](https://github.com/user-attachments/assets/d3f402a8-ce58-4d08-bfa5-9ee887a9d17b)

**Comment by MillenniumFalconMechanic** [comment]
Thanks @jpaten! Are the unchecked checkboxes in the description still outstanding?

**Comment by mrtopsyt** [comment]
@MillenniumFalconMechanic whoops, I forgot to check those! Thanks for catching it.

**Comment by MillenniumFalconMechanic** [comment]
LGTM, thanks Jonah!
