### ISSUE TITLE
Add cell_suspension.selected_cell_type to the browser facets

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#512]
@malloryfreeberg  we are collecting the requirements for indexing and displaying selected_cell_type.
Can you provide some answers to the following questions and add any additional context? 

Thanks,

 
What table should we add this to in the ui?

Should this be a facet as well? 

What category should the facet go under?

┆Issue Number: HCAB-418

**Comment by hannes-ucsc** [comment]
> What table should we add this to in the ui?

It's a facetted UI so … every table?

**Comment by malloryfreeberg** [comment]
> > What table should we add this to in the ui?

> It's a facetted UI so … every table?

Agree with Hannes on this point. Users will want to know what cells types are represented in a project, in a sample, and by a particular fastq or analysis results file. e.g.:
- "I want to see all the projects that imaged cardiomyocytes."
- "I want to see how many primary brain samples the HCA has with data for peripheral neurons."
- "I want to download fastq files for all CD45+ immune cells in the HCA."

> Should this be a facet as well?

I'm still not certain why some fields are faceted and others are not. To answer your question about collecting requirements, I would say (and @gabsie and @adriennes have the feedback to support this but I'm happy for them to expand upon it) that **users will want to be able to search the HCA DCP for a cell type of interest and find raw/processed data that represents that cell type**. How this gets implemented in terms of facets is unclear to me. 

> What category should the facet go under?

I'm not sure what is meant by "category" here - can someone clarify? 

To provide some additional context, not all projects will have the `selected_cell_type` field filled in. It is an optional field at the moment for a couple of reasons. First, not all projects do a cell type selection (what the metadata refers to as "enrichment") as part of the experiment. Rather, the experiment just analyzes all cells from a particular sample. Second, some cell types are identified post-analysis instead of prior to analysis. At the moment, the HCA metadata does not collect post-analysis information from contributors. This *could* change in the future, but AFAIK there isn't anything on the immediate roadmap for this.

**Comment by adriennes** [comment]
> I'm still not certain why some fields are faceted and others are not. To answer your question about collecting requirements, I would say (and @gabsie and @adriennes have the feedback to support this but I'm happy for them to expand upon it) that **users will want to be able to search the HCA DCP for a cell type of interest and find raw/processed data that represents that cell type**. How this gets implemented in terms of facets is unclear to me.

Just confirming that yes, this is one of the most common use cases we hear.  The example faceting searches Mallory listed are great illustrative examples of what users have said they want to do.  
 
> > What category should the facet go under?

I'm not sure it fits in any of the existing facet categories in the browser, probably it should be a new category.  We may want to consider combining "Specimen" and "Donor" categories to make room for a "cell type" category.

**Comment by malloryfreeberg** [comment]
@adriennes in your user research, did you get a sense of how often people wanted to search by (1) a cell type name (e.g. cardiomyocyte), (2) a set of cell surface markers (e.g. CD45+), or (3) a set of expressed genes (e.g. a list of 5 highly expressed gene in cell type *X*)?

Scenarios 1 and 2 could be supported by metadata, but scenario 3 will require searching through expression matrices and might be very difficult...

**Comment by adriennes** [comment]
@malloryfreeberg - we've heard all of those search requests, but I don't think we have an accurate count of which is most important/popular.  We can incorporate that question into the Phase 2 beta, since we'll have a larger number of participants to ask.  
I would say that supporting **any** of these search functionalities seems better than supporting none.  If Options 1 and 2 are currently supported by the metadata, that seems like a good place to start...

**Comment by malloryfreeberg** [comment]
> supporting **any** of these search functionalities seems better than supporting none

Agree 10000%!

**Comment by malloryfreeberg** [comment]
@adriennes I think quantifying (if possible) the types of search requests users have would be very useful to helping us prioritize both metadata schema updates to support the requests and how/what the Browser/Azul displays/indexes for users. I know there's already a lot to get done in Phase 2, but if this could be incorporated in I think it would be very valuable :)

**Comment by NoopDog** [comment]
Hi @theathorn Looks like we have enough interest and solid requirements to schedule this one. 
Thx,
D
