### ISSUE TITLE
Use Data Store Collections for data citation

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#550]
1) making a collection per project to coincide with the overall DCP release
2) include analysis results in that collection
3) link to that collection on the project page.

The Collections service provides a permanent reference to a point-in-time snapshot of an arbitrary collection of data and metadata.

A DOI can be minted to point to a Collection, removing the need for any external 3rd party storage of data such as file manifests or metadata tsv files.

**Comment by theathorn** [comment]
Suggestion to use the Project UUID for the Collection.

**Comment by lauraclarke** [comment]
Hi @theathorn It would be great to see the requirements analysis for your plan? 

From a naive point of view, I am confused why the plan doesn't make projects citable as soon as they are publicly visible on the data portal? 

On our previous email conversation about this matter @gabsie pointed to some great examples on how this could work

This is a document from her email on March 20th about how existing services meet this requirement

https://docs.google.com/document/d/1eM80EGe3T4VTU5hyBUKCGdN17k_MMxsRcWwHBB-54n4/edit?usp=sharing

**Comment by theathorn** [comment]
@lauraclarke The requirements are taken from @gabsie document with further input from OC member @benedictpaten (and PL @briandoconnor). Benedict's comments are in the parent Epic with they key point being "You should only be minting (DOIs for) immutable objects. Anything that is subject to change without versioning should not have a citation".

This is a key requirement (immutability) . If we are providing a single citation reference per project (e.g. on the Project Details page) then we should do so once all the data for that project is no longer subject to change (this includes both primary and secondary analysis data and metadata files). Once the citation ID is provided then any subsequent changes to the project (e.g. AUDR changes) would not alter what the citation refers to.

Allowing for multiple citations for a project (e.g. citation_1 refers to the data as of 2019_04_13 while citation_2 refers to the data as of 2019_05_01) is a much more complex problem to solve and is not achievable within the Q2 time frame. The roadmap document (https://docs.google.com/document/d/1rZnDfUdqWagSFiX5BpBITu1JcizXD1v77UDV-qLSmpg) asks for "project level citation functionality". The simplest way to deliver this may be to ask submitters when their submission is complete and ready for citation and then generate a single project citation for a snapshot of that data. With SS2 there are many bundles being ingested and there's no easy way to know when the last one has been ingested (e.g. files show up in the browser as each bundle is indexed).

**Comment by lauraclarke** [comment]
I think there has been some miscommunication here. Happy to get on a phone call and talk this through in more detail if that is helpful.

The first valuable thing in this context is a URL which doesn't change so when people refer it still works sometime later and still refers to the same project and then there is something on the page which is pointed to that provides a copy and pasteable snippet which can be used as the citation, the examples the services @gabsie points to are a great starting point for the design.

The awesome version of this feature is a DOI which refers to a project page with a full provenance trail and the ability to get to previous versions of the project but that isn't what is expected to be delivered in Q2, at least to my understanding nor as I understand it does each version need its own DOI.

I asked the question as it isn't clear what value the collection service adds in this context. 

The collection service will enable the community to share arbitrary sets of data in the HCA DCP and move forward the efforts of both the whole atlas and individual biological communities but that seems like quite a different value proposition to the provision of project level citations. 

If I have got the purpose of the collection service wrong I would love to hear more about what value it is aiming to add.

**Comment by lauraclarke** [comment]
It is also worth noting that data under a DOI isn't totally immutable and can change. It is possible to support versions

The DOI FAQ says this https://www.doi.org/faq.html

> 7. If I have assigned a DOI name and I make a change to my material, should I assign a new DOI?
>
>The IDF does not have any rules on this. Individual RAs adopt appropriate rules for their community >and application. As a general rule, if the change is substantial and/or it is necessary to identify both >the original and the changed material, assign a new DOI name.

Reading figshare's advice to updating data for submitters is a reasonable guide to the sort of process we might want to adopt once we have a more fully features systems, as I said above these are not first iteration, this quarter requirements

https://knowledge.figshare.com/articles/item/can-i-edit-or-delete-my-research-after-it-has-been-made-public

**Comment by gabsie** [comment]
Hi, everyone
I also don't mind jumping on a call. 

I may not be understanding the necessity of the key requirement around immutability. 

With regards to changing after submission, I think it's normal to expect for some of the data to change within the project (any of the AUDR, e.g., deleting or updating metadata and files etc). 

With figshare, you get a unique URL and a "reserved" DOI - if you wanted one, at the very beginning, without having even entered data or metadata for the project. 

Both are per project, and refer to all the data which is ultimately going to be in that project.
Let me know if I am not aware of some specifics.

Gabby

**Comment by hannes-ucsc** [comment]
I would like to be on that call, too.

**Comment by NoopDog** [comment]
Hi @gabsie are you sure Figshare projects have DOIs?

 Looks like Figshare has DOIs for `Items` and `Collections` and that items and collections are versioned if they undergo meaningful changes.

It also looks like,  `if the version changes then the DOI changes as well` and they encode the version information  in the DOI suffix. 

For HCA  of course, the goal is to be able to get the exact same data set that was used for some study to support reproducing the study or doing additional work with the study data. 

The exact same data means:

1. the same number of bundles.
1. the same bundle ids 
1. the same bundle versions.

For the matrix service this might mean the exact same matrix. Or the exact same matrix software version run over the exact same manifest.

If someone changes a data or metadata in a project in HCA, we  would would need a way to then change the project version and then create a new DOI for the new version. That way, the old DOI always refers to the same "immutable" collection of bundles at a specific version. 

Since HCA does not currently support versioning the proposal is to take a "snapshot" at a point in time and use that snapshot as a version that can be assigned a DOI. This creates a set of files that have all of the input, the analysis outputs, the matrix service outputs and creates a citable version.

I don't think we can drop the immutability constraint as this is core to supporting reproducibility of but there may be ways to create immutable artifacts more easily / frequently if we prioritized it.

**Comment by gabsie** [comment]
Hi, @NoopDog and all,
You are right - it's **not Project** but a Dataset that has a DOI in figshare, and that is actually an **Item** (examples of items are dataset, files, tables). So yes, items have DOIs, as well as **Collections** of Items. I think our Projects actually resemble figshare Collections at the moment, they contain multiple items.

So - I think we're discussing two things, when discussing immutability. As I was mostly thinking about the first scenario below previously, let me lay them both out.

 **A. On a Project level**
**Scenario:** A submitter needs to change items from their project: data files, metadata, changes to funding info, enriching metadata, changing an ontology item. This is inevitable after publication, and is happening now. The needs for project changes is why we are doing the Updates development now and improving it in the future. A data consumer needs to reference a version of the project as it is at this point in time.

**Need:** There is a need to track these project versions as immutable collection of files from one project when it's being referenced, so that science based on using that whole project could be reproducible and trustworthy. A project exists as latest version from a certain point in time when it got published on HCA. Previous versions can be tracked, from previous points in time.

I would also say a per project/per paper reference seems the most common way people use data from repositories and publications at the moment, so there is the sense of frequency and familiarity here.

Urgency: high, this is happening 
Scientific consequence: high
Occurrence: frequent

**How:**
1. Constant URL for the Project/Constant URL with variables in the URL for versions, i.e. date
2. Base DOI with Base DOI plus versions 
3. Other options?

 **B. On a slicing across Projects level** 

**Scenario:**  A consumer uses and needs to reference data from only a slice of data across projects with their current versions  for further scientific analysis and conclusions. E.g. give me all pancreas samples across 3 projects and I am going to use and reference only them.

**Need:** There is a need to track this immutable collection of files from several projects in their current versions, at a certain point in time when it's being referenced, so that science based on using the files from several projects could be reproducible and trustworthy. 

Urgency: ?
Scientific consequence: high
Occurrence: ?

**How:**
1. Ideas? ...
2. A constant URL for this specific collection of files from diff projects, in this point in time, which is reproducible?
2. A list of Constant URL-s for the Project versions used, with references to the specific files used (manifest + project identifiers?, specific version of the Matrix service)
3. A list of Base DOI-s for the Projects used, with references to the specific files used
4. Other options?

I am open to discussing any of the above, of course. I wanted to outline the above for my understanding first, and hopefully it can help others, too. I feel that as a very first step right now we can go and at least have that unique URL for project. It is easy to do, and we know we're going to need it not only for referencing, but also for easy sharing, etc. I see it as a skateboard version of where we want to be. 
The need for versioning is an immediate step after that, and following from the base step above. 

Would a person be able to reference data from several projects at a point in time by those unique URLs? It would be clumsy, but yes.

I also think for the future we should try and brainstorm/form a policy on types of updates which would trigger a Project version, and ones which shouldn't. E.g. would a spelling correction have to trigger a version? The figshare link explains everything around that very well: 

https://knowledge.figshare.com/articles/item/can-i-edit-or-delete-my-research-after-it-has-been-made-public

Happy to hear more from everyone. I think after the description above, the first things to discuss are:

-  Is the above problem space outline correct and full? If not, add to it
-  Priority and timelines - what are the needs, times and costs for the immediate future, and for straight after?

All the best
Gabby

**Comment by lauraclarke** [comment]
Thanks for the great post defining the problem space. I think this highlights the need for a conversation about what type of updates geniuely change the dataset from a reproducibility perspective and what types of edits are more improvements/error corrections and don't affect how reproducible the data referred to by the url is. I really like crossrefs video about their crossmark service for giving a summary of the second type of edits https://www.crossref.org/services/crossmark/

Right now, I suggest it might be good to take a step back and consider what is needed now to improve from can already do and can be delivered in the timeframe of this quarter and what foundational work can be done looking past the end of this quarter to a more fully formed solution?

Looking at the project pages as they stand, if a user is writing a paper or other documentation about their own use of data from the HCA DCP copying the project URL and title such as 

Assessing the relevance of organoids to model inter-individual variation
https://prod.data.humancellatlas.org/explore/projects/d96c2451-6e22-441f-a3e6-70fd0878bb1b

and maybe if they are paying attention to the contributors those too. An immediate improvement would be a section titled how to cite this project or similar which gave the recommended URL, title and author list

Future features which may or may not be possible this quarter would be provenance trails which demonstrate what updates have happened and when and DOI assignment to projects, collections or whatever associations data releases have as defined by the new DCC team.

On DOI assignment for what it is worth. We not only need to decide to what we assign DOIs and when but we also need a policy about what is an update and what triggers a new version (like Figshare) or a brand new DOI (see https://figshare.com/articles/Attraction_of_males_to_females_in_the_fourth_larval_stage_L4_or_as_adults/1597650 for an example of Figshare's versioning). 

We also need to think about which registration authority are we going to use? (http://www.doi.org/registration_agencies.html), do we go with a service provided by one of our institutions (EBI is already registered with Crossref), how are they paid for? How rapidly should we give things DOIs balancing the immediate need for people to want to cite publicly accessible data with the fact that in the early stages of submission there may be more frequent updates?

All of these things need to be considered.

**Comment by theathorn** [comment]
Superseded by DCP/2 - closing.
