### ISSUE TITLE
Generic tertiary portal hand-off

### ISSUE THREAD

**Issue by briandoconnor** [DataBiosphere/data-browser#6]
┆Issue Number: HCAB-4

**Comment by briandoconnor** [comment]
* spam the whole HCA and ask who's interested in making a portal and register your interest in interacting/training with HCA... talk to Fabian about this.... Tim and Irene about generating this list.
* Jenn is checking into a jamboree in early april
* late april there's a red box meeting that I asked to present this at

**Comment by theathorn** [comment]
Update: above items are complete and Done means completion of Collections API and integration with at least one tertiary portal.
Need another demo from Carlos and Tim/Marcus on how to program to portal/Collections API.

**Comment by theathorn** [comment]
@briandoconnor status on this?

**Comment by eweitz** [comment]
https://github.com/HumanCellAtlas/data-portal-content/issues/19 asks about hand-off, so please comment there when hand-off is ready for portals.  Or ping me, and I'll do so!

**Comment by theathorn** [comment]
From #32:

As a user, I would like to handoff a collection to a tertiary portal for further analysis/visualization

There needs to be an API endpoint responsible for sending the reference of the collection to the redbox of choice.

**Comment by theathorn** [comment]
HCA Functional requirements (https://docs.google.com/document/d/1dvz7ij5JDAHSFZmpAHsw3_xbDge-EEhuLcvA5SIkhc8) states on p5: "Tertiary Analysis portals that will take the file manifest produced by orange box search and run additional analysis". I believe this is the intended solution before Data Browser integration with the Collections API is available.

**Comment by hannes-ucsc** [comment]
➤ Trevor Heathorn commented:

Hand-off to Terra is covered under epic AZUL-380.

**Comment by theathorn** [comment]
Priorities:
  1) Terra (databiosphere/azul#606)
  2) SCP (#545 & #761)
  3) Max Haeussler's UCSC Cell Browser

**Comment by theathorn** [comment]
From @hannes-ucsc :
I would not consider the spec officially released. Note that the spec still resides in the rfc folder of the source tree. I do not feel comfortable releasing the spec until we have fully implemented all endpoints. Until we have done so, the spec should be considered a draft because the implementation may require changes to the spec.

The location of the draft on the develop branch is https://editor.swagger.io/?url=https://raw.githubusercontent.com/DataBiosphere/azul/develop/rfc/portal-registration-api.yaml

**Comment by NoopDog** [comment]
Obsolete
