### ISSUE TITLE
Implement Paging for large results

### ISSUE THREAD

**Issue by caaespin** [DataBiosphere/data-browser#61]
As a user I would like to be able to page through large a result set.

The repo: https://github.com/DataBiosphere/cgp-dashboard-service

DOD: The web service implements `search_after` method in ElasticSearch. If data set is less than 10K documents, use regular paging, but if more than 10K, use search after method. Unit test included.

┆Issue Number: HCAB-109

**Comment by caaespin** [comment]
UPDATE: Blocked by data. Jim to put an example JSON response of the REST API.

**Comment by jvlasblom** [comment]
# Specification
The first call, without any arguments, will issue a query using to/from. If ES returns the total number of results as < SEARCH_AFTER_THRESHOLD, then the returned pagination section will contain:
```
{count, total, size, from=<integer>, page, pages, sort, order, search_before=[], search_after=[]}
```
and one can infer that to-from pagination can be used.  Otherwise, "search_after" pagination must be used.  The return pagination section in that case will contain:
```
{count, total, from=null, page=null, size, search_after=[sortfield, _uid], search_before=[], pages, sort, order}
```

These fields are defined as:

count, total, size, pages, sort, order:  Unchanged

from: unchanged if total number of documents < SEARCH_AFTER_THRESHOLD, otherwise null.

search_after: [] if total number of documents < SEARCH_AFTER_THRESHOLD or if there are no 
more documents after the last one returned in the hits section, otherwise [sortfield, _uid]. Here sortfield corresponds to the value of the currently selected sort field for the last entry on the current page, and _uid is the elasticsearch _uid for the last hit on the current page.

search_before: [] if total number of documents < SEARCH_AFTER_THRESHOLD or if there are no more documents before the first one returned in the hits section, otherwise [sortfield, _uid].  Here sortfield corresponds to the value of the currently selected sort field for the first hit on the current page, and _uid is the elasticsearch _uid for the first hit on the current page.


If search_after.length > 0, to navigate to the next page the array should be passed in the GET request.  e.g.:
```
GET /repository/files?search_after=<search_after[0]>&search_after=<search_after[1]>
```
If search_before.length > 0, to navigate to the previous page use:
```
GET /repository/files?search_before=<search_before[0]>&search_before=<search_before[1]>
```
It is an error to pass both search_before and search_after in the GET request.

# Examples
Examples of pagination objects returned by executing GET /respository/files with various arguments, assuming 8 total documents, a page size allowing 2 hits per page, and a SEARCH_AFTER_THRESHOLD of 2 (...so search_after pagination will be used):
```
...with no args:
{count=2, from=null, order="desc", page=null, pages=4, search_after=[sortfield, _uid], search_before=[], size=2, sort="file_id", total=8}

...with search_after, using above returned search_after:
{count=2, from=null, order="desc", page=null, pages=4, search_after=[sortfield, _uid], search_before=[sortfield, _uid], size=2, sort="file_id", total=8}

...with search_after such that the last page is returned.
{count=2, from=null, order="desc", page=null, pages=4, search_after=[], search_before=[sortfield, _uid], size=2, sort="file_id", total=8}

...with search_before, such that the second last page is returned.
{count=2, from=null, order="desc", page=null, pages=4, search_after=[sortfield, _uid], search_before=[sortfield, _uid], size=2, sort="file_id", total=8}

...with search_before, such that the first page is returned.
{count=2, from=null, order="desc", page=null, pages=4, search_after=[sortfield, _uid], search_before=[], size=2, sort="file_id", total=8}
```

In these examples, sortfield is the *value* of file_id for either the first (for search_before) or last (for search_after) document returned on the current page.
