### ISSUE TITLE
Report broken subgraphs

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#622]
Create a (public, non-linked) status page for every bundle which Azul fails to index for any reason.
e.g. https://data.humancellatlas.org/explore/bundle_status

**Comment by theathorn** [comment]
@NoopDog Suggestion from @briandoconnor to perhaps add a link to https://tracker.data.humancellatlas.org/ from the Data Browser.

**Comment by theathorn** [comment]
@hannes-ucsc Is there a mechanism for Azul to report any failed/bad bundles that would be visible to the Data Operations teams? If not, what would you suggest?

**Comment by hannes-ucsc** [comment]
Given a recently ingested project, the tracker should be the first place to check. If the tracker persistently reports a mismatch (transient mismatches are to be expected), a ticket should be filed against Azul. If the tracker reports that all bundles are present in Azul, someone (wrangler or DataOps person) will need to sanity check the Data Browser for that project. Check cell counts, number of files, project details etc. This can't be a responsibility of the Azul/Data Browser team because when bundles are indexed completely but in a way that doesn't match the submitter's intent, one would need to know that intent to detect a discrepancy between expected and actual behavior. Sometimes the discrepancy is obvious, but not always.

We will also soon have a health check and associated Slack alarm that fires when there are any indexing failures in Azul's fail queue (https://github.com/DataBiosphere/azul/issues/1168, PR https://github.com/DataBiosphere/azul/pull/1178). The alarm would only tell you that there are failed bundles and not which ones (it may tell you how many) but we will implement a procedure where the Azul release engineer pulls the failures out of the fail queues, triages and consolidates them and creates a ticket for each type of failure, listing the individual bundles that failed.

**Comment by theathorn** [comment]
@briandoconnor Does https://tracker.data.humancellatlas.org/ satisfy the requirement for this ticket? If not, what more needs to be added?

**Comment by theathorn** [comment]
9/5 Storytime with BrianO, Trevor, Hannes & Dave:
  - Azul to expose "failed bundles" queue via a service end point.
  - Data Browser to provide a "bundle status" page.

**Comment by briandoconnor** [comment]
We discussed this today and I gave my feedback to Hannes and Trevor.
