### ISSUE TITLE
Search is not working correctly in prod

### ISSUE THREAD

**Issue by zperova** [DataBiosphere/data-browser#662]
To reproduce - go to https://prod.data.humancellatlas.org/explore/projects
Start typing Tabula Muris in the Search box
choose Tabula Muris from the suggested list

The table with the metadata doesn't change listing all the datasets even though there is only one project selected.

Expected behaviour: 
Table only shows metadata for one dataset which is Tabula Muris

Screenshot:
![Screenshot 2019-05-30 at 16 57 33](https://user-images.githubusercontent.com/38244059/58646121-a437ca80-82fc-11e9-9c8a-eb9b3356bd10.png)

**Comment by theathorn** [comment]
Actually it's working as designed..
 
When a project is selected a checkbox is filled in next to the project line but all the other projects remain selectable. Otherwise the Project view would always reduce to a single project.
Adding @adriennes and @gabsie to comment from the UX point of view and @NoopDog for the UI design.

**Comment by NoopDog** [comment]
Hi @zperova thanks for raising the issue.

Its on our roadmap to:

1. Improve the project search
1. Improve how we indicate which projects are selected
1. Better integrate project search vs project browsing vs viewing selected projects. 

The current implementation is working as designed. Originally we only showed the selected projects in the projects tab, but as @theathorn mentioned that makes it impossible to select more than one project in the table (you can still select additional projects in the search but that is difficult for people to discover).

We will be doing some mocks and user testing for this in the coming weeks. Feel free to follow along chime in on the UX slack channel. 

Cheers,
Dave

**Comment by adriennes** [comment]
I think this is a good catch.  The expected behavior when selecting the project using the checkbox from the list may be different than when selecting a project from the facet or search.  

Agree with @NoopDog that this is a good one for some light user testing - could we add this to the list for next week?

**Comment by zperova** [comment]
@theathorn Thanks for the explanation, I see your point. I imagined the search would work the same as when one searches for an organ - it shows the datasets that have this organ and does not select any of these. But that doesn't allow selection of multiple datasets.
@NoopDog @adriennes I wonder whether an enhancement to the current design of bringing the dataset that is searched for to the top of the list is easy to implement? I will keep an eye on the UX channel for the results of the mocks and user testing.

**Comment by NoopDog** [comment]
Yes @zperova that is the direction we are thinking of. Will let you know when we have some mocks to review.

**Comment by NoopDog** [comment]
created #665 to track adding the selected projects to the top of the projects list.
