### ISSUE TITLE
Display author information with project title on project pages

### ISSUE THREAD

**Issue by daniwelter** [DataBiosphere/data-browser#694]
As a user of the data browser, I would like to see at least the lead author in the list of attributes at the top of the page, ideally right below project title, rather than just at the bottom below the description. This would be more intuitive, especially for projects with a long description.

**Comment by theathorn** [comment]
Dani, is this the project.publications.authors metadata filed, which is an array?

**Comment by jlzamanian** [comment]
As a first time user of the site, author information was one of the first things I looked for on the project page. I would have preferred it be more prominent. Note that it's actually the lab head (typically the corresponding author) that I would be looking for. 

One possible format for long lists of authors is "first couple of authors ... lab head".

**Comment by daniwelter** [comment]
@theathorn It is, although you could filter by corresponding_contributor=True to only display the corresponding author.

**Comment by NoopDog** [comment]
The project detail page is currently being updated to match this  mock here:

https://chanzuckerberg.invisionapp.com/share/CHSEDSO56SM#/367521680_Explore_-_Get_Data_-_Project_Detail_-_New_-_Counts

Highlighting the contacts / contributors was not a goal for this (highlighting the downloads was) however the contacts/contributors are slightly more prominent in this layout.

We can take a look at making the contacts/contributors more prominent as we build this out. I will also reach out to a few folks to see if this is a priority.

The lab, author are deliberately not exposed as top level facets (although you can search by them) because as, I understand it, the data is meant to stand on its own and we want to avoid burying content that is not from a well known institution or lab.

**Comment by jlzamanian** [comment]
@NoopDog I see. The decision to not prominently display the lab makes sense in the context of an atlas with defined standards.

**Comment by zperova** [comment]
@NoopDog I like the new layout of the Project detail page. I like the fact that the authors list is right after the project description and that the various project details are next to it. It provides a clearer view. 

I have a suggestion on the contributor's list, which I expressed here: https://github.com/HumanCellAtlas/data-browser/issues/706

**Comment by theathorn** [comment]
Handled by the otehr tickets in the Epic.
