### ISSUE TITLE
Access tsv files via https over Cloudfront

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#708]

**Comment by NoopDog** [comment]
Just copying from slack to here

Dave Rogers [11:47 AM]
I just added “list bucket permissions” on the TSV S3 Bucket (dev.dev.url.data.humancellatlas.org) so that when we check for a file that is not there, we get a 404 Not Found instead of a 403 Forbidded when doing a head request for a file that does not exist. I will do this to all the TSV buckets through to prod unless there are any objections. What else is in this folder? Will making its contents listable bother any usage?

**Comment by NoopDog** [comment]
@GPelayo Looks like I will need to add a top level directory in the tsv bucket to hold the tsv directory and the matrix directory. I propose a structure like this:

/project-assets/project-metadata
/project-assets/project-matrices

Will this work for you and your scripts?

I think I can modify the files manually in dev to test this structure. 

Cheers, 
D

**Comment by GPelayo** [comment]
@NoopDog It shouldn't be a problem to implement the project-assets directory. But are there plans for other top-level directories in the bucket?

**Comment by NoopDog** [comment]
No other top level directories to add. Thx

**Comment by NoopDog** [comment]
@GPelayo ok then.. can you modify the tsv and matrix upload scripts to use the new buckets like

dev.project-assets.data.humancellatlas.org
ux-dev.project-assets.data.humancellatlas.org
integration.project-assets.data.humancellatlas.org
staging.project-assets.data.humancellatlas.org
project-assets.data.humancellatlas.org

Can you also run the script to populate the /project-assets/project-metadata directory with tsv files for dev so I can continue testing the setup.

I will manually setup CORS on these folders by copying the config from the old buckets. 

Thanks!

**Comment by NoopDog** [comment]
@GPelayo I forgot to include the ux-dev.project-assets.data.humancellatlas.org environment. I just added it above. Thanks, D

**Comment by NoopDog** [comment]
@GPelayo the above buckets all exist and the code to access them is deployed through to staging. Once the tsv and matrix files are uploaded to these buckets in the appropriate directories the tsv download and matrix file detection and download should work again.

Cheers and thanks for your help with this.
