### ISSUE TITLE
Incorrect display of the HCA data curators

### ISSUE THREAD

**Issue by zperova** [DataBiosphere/data-browser#823]
In this dataset an Array Express curator (Anja Fullgrabe) got into the list of HCA data curators:

https://data.humancellatlas.org/explore/projects/f83165c5-e2ea-4d15-a5cf-33f3550bffde

This could be if the decision to list HCA data curators was made on searching by the email address rather than the presence of the 'HCA' or 'Human Cell Atlas" in the project_role.text as Array Express is an EBI resource.

**Comment by NoopDog** [comment]
Yes email was used instead of project role text as the browser client does not have access to the browser role text. 

Really what needs to happen here is the role needs to be added to the role ontology as a single unit and not split over the the ontology and ontology text. 

If we can not use email then perhaps for now Azul can implement the heuristic combining the ontology and ontology text and make a fake role for us to filter by.

We can remove the HCA Data Curators section until either Azul implements the heuristic or the role is properly represented in the metadata and the heuristic is no longer required. 

@theathorn @hannes-ucsc how would you like to proceed.

**Comment by NoopDog** [comment]
We will hide this until we have back end support.

**Comment by gabsie** [comment]
Isn't it better to just leave it and call this Data curators, like it was. After all, all these people did the work.

**Comment by NoopDog** [comment]
@gabsie great idea. Yes we will just change the name to Data Curators for now until we have a support in the back end to distinguish between HCA and other data curators.
