### ISSUE TITLE
Normal is not a known disease. 

### ISSUE THREAD

**Issue by ambrosejcarr** [DataBiosphere/data-browser#864]
"Normal" is not a "known disease". None would be more appropriate. 
![image](https://user-images.githubusercontent.com/5239152/64476054-5b43ad80-d158-11e9-8ef8-c86406cd02fd.png)

**Comment by lauraclarke** [comment]
I agree that normal is not a known disease it is the generally accepted term to label research participants without any known diseases. https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000461

I noticed for HipSci, an iPSc project where we used normal as the ontology term for no known disease we called it disease status rather than known disease. 

Happy to have a discussion about the best way to label this field, we can always change the friendly name

**Comment by ambrosejcarr** [comment]
> I agree that normal is not a known disease it is the generally accepted term to label research participants without any known diseases. 

Totally agree. Would be happy with "Disease Status".

**Comment by lauraclarke** [comment]
Issue created in the metadata schema https://github.com/HumanCellAtlas/metadata-schema/issues/1124

**Comment by theathorn** [comment]
@NoopDog I think we can change the Data Browser column name from "Known Diseases" to "Disease Status" independently of the metadata schema change. Or are we deriving the column name from the metadata?
