### ISSUE TITLE
Support for mouse data in the matrix service

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#895]
The MS will produce separate matrices for mixed-species projects (e.g. when a project has a mix of human and mouse data).

Marcus to send email on proposed response to request from DB to MS which includes multiple species.

Proposal is to generate matrices whose filenames include the project_uuid and species name.

**Comment by mckinsel** [comment]
For multiple species, here's what I was thinking:
- We would really strongly prefer this change to be non-breaking so we can stay on `v1` and not have to do a whole new release of the interface
- The _usual_ case isn't really changing: most queries should only return human data

Recall that the current response from `GET /matrix/<request_id>` looks like this:
```
{
  "eta": "can be ignored",
  "matrix_location": "url to matrix file",
  "message": "something helpful about what happened, esp if there's an error",
  "request_id": "uuid of the request",
  "status": "Complete, In progress, etc"
}
```

The meaning of `matrix_location` would become `url for the human matrix file`, and we would add another field `non_human_matrix_locations`. That would be an object with keys that are the latin name of the non-human species and values that are urls to the matrix files. So something like this:

```
{
  "eta": "",
  "matrix_location": "https://..../human_matrix.loom",
  "message": "Looking good!",
  "request_id": "<uuid>",
  "status": "Complete",
  "non_human_matrix_locations": {
    "Mus musculus": "https://..../mouse_matrix.loom",
    "Danio rerio": "https://..../zebrafish_matrix.loom"
  }
}
```

Note that "matrix_location" xor "non_human_matrix_locations" can be empty If there are no human or non-human cells in the request, respectively.

**Comment by mckinsel** [comment]
For the s3 uploads:

Currently, matrices are uploaded to `s3://project-assets.data.humancellatlas.org/project-assets/project-matrices/<project_uuid>.<format>`, where `format` is in `[loom, csv.zip, mtx.zip]`

We now may have multiple matrices for the same project_uuid and format combination because of multiple species. So, we can change the path to `s3://project-assets.data.humancellatlas.org/project-assets/project-matrices/<project_uuid>.<genus_species>.<format>` where `genus_species` is the lower-cased, underscore-joined latin name of the genus and species. For example, `homo_sapiens`, `mus_musculus`, or `danio_rerio`.

In addition, the `Content-Disposition` of the file will become `<project_short_name> <genus_species> <creation datetime>.<format>`

**Comment by theathorn** [comment]
@NoopDog @MillenniumFalconMechanic 
Is the above proposal from @mckinsel  the agreed upon approach?
I've marked the Browser work as blocked until the Matrix Service implements these changes.

**Comment by NoopDog** [comment]
Yes @theathorn @mckinsel this looks good. Thanks for writing this up clearly and keeping this non breaking.

**Comment by brianraymor** [comment]
If I understand correctly, the design has changed from the one proposed [above](https://github.com/HumanCellAtlas/data-browser/issues/895#issuecomment-534749720) to the one discussed in [the-matrix-reloaded](https://humancellatlas.slack.com/archives/CC9AR11T7/p1570561176097300) - it appears that there are _non_human_request_ids_ that are returned in the POST response that can then be individually queried in the GET.
