### ISSUE TITLE
Review Current Site and Create Update List

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#90]
┆Issue Number: HCAB-133

**Comment by happyimadesignr** [comment]
Here's my review of the Browser. I marked a "P" in front of the items that are priority to me.

- [x]  P - Data Browser - Make filters, counts, download button sticky. See design: https://chanzuckerberg.invisionapp.com/share/JQKKKO4B6Z5#/297570103_2-2-1_Explore_-_Data_Copy_17

- [ ]  Data Browser - Tooltip animation too extreme

@happyimadesignr can you please advise on preferred animation style
@frano-m it pops in too fast                       
                       
- [x]  Data Browser - Pagination needs to be updated. See design: https://chanzuckerberg.invisionapp.com/share/UQKKKQKWKFH#/299232552_2-0-0_Explore_-_Data_Copy_2

@happyimadesignr can you please advise for mobile view pagination style - if page number is three digits the little blue box won't look so cute - it won't be square and the longer numbers will take up more horizontal space

![image.png](https://images.zenhubusercontent.com/5ac463024b5806bc2bcd91dd/a847b3ef-8662-4fd3-a8ae-d157d85273e5)                       

Doesn't look to bad - let me know if you want me to go ahead with this implementation?

@frano-m looks good      

@NoopDog what was the reason for why we have to have pagination with only < 1 of 91 > rather than < 1 2 3 4 5 >                                        

![image.png](https://images.zenhubusercontent.com/5ac463024b5806bc2bcd91dd/69c8fca7-c774-4498-9737-0a5a39be23d7)

- [x]  P - Data Browser - Pagination - Remove top pagination

- [ ]   Data Browser - Table needs to match design

@happyimadesignr Is this data related? Noted in our google doc - I mentioned table will need updating when data comes in.  Also hover over file type and ticks probably after F2F.

@frano-m I think it was just the file type and the age and age unit combo        
@happyimadesignr Age unit now combined - file type for post F2F (with hover)                       
                       
- [ ]  P - Data Browser - Filters - Method is missing Molecule and Sequencing Approach. Imaging Approach for later.

Data related?

@frano-m I'm not sure. @NoopDog do you know?

- [ ]  P - Data Browser - Filters - We need friendly names from Ingest team ASAP 

- [x]  P - Data Browser - Filters - Donor filter dropdown should be 4 across rather than 3.

@happyimadesignr sorry - I was trying to keep the drop down within the select box area - rather than bleeding over to underneath the search box - now resolved                       

- [ ]  P - Data Browser - Filters - Specimen is missing Specimen Type and Storage Method

Data?

@frano-m I'm not sure. @NoopDog do you know?

- [x]  P - Data Browser - Filters - More dropdown - Terms under Protocol should wrap to 2nd line rather than “..."

@happyimadesignr Note Protocol data is currently using underscores rather than spaces - I did an ellipsis on this one only (the others wrap) - I've now changed it to a break-word - which we will need to review if the new data comes down differently.             

- [ ]  P - Data Browser - Filters - All dropdown titles should wrap to 2nd line rather than "..."

@happyimadesignr  Need advise on preference - had them originally wrapping but it looked pretty dense with the count in there are well.  Also, would need to fix a height for the facet titles and assume for wrapping as some Facet names wrap and others don’t so when you have a mix of some wrapping and some not it doesn’t look too hot (i.e. the first term listed are no longer lined up).  Also, do you want count top or bottom aligned?

@frano-m Let's wrap them. Why do you need a fix height to the titles? Align the counts to the top line =]

@happyimadesignr fixed height for titles because if you see image below here, the terms underneath the facets don't line up - some titles only need one line and therefore their terms start higher than the the facets that need two lines... you ok with the jiggle or do you want everything to line up?                                              

![image.png](https://images.zenhubusercontent.com/5ac463024b5806bc2bcd91dd/343d5f68-01ab-406b-965d-b71786a98174)

![image.png](https://images.zenhubusercontent.com/5ac463024b5806bc2bcd91dd/1bedc203-f32e-436a-b9aa-addc0a0ac068)
        
- [ ]  P - Data Browser - Filters - Fix how ages are displayed. At least should be in order from lowest to highest.

@NoopDog
            
- [ ]  Data Browser - Filters - Needs heavier type weight

@happyimadesignr                        
Is this the filter name inside the select box?
Requested: Monstserrat, regular 13px, character spacing 0.4px (was Gotham Book, 13px, 0.4 character spacing).
Implemented: Montserrat, font weight 400 (regular), 13px, character spacing 0.4

I've included Montserrat now as a google font so I'm hoping it should be correct?

@frano-m let's revisit this in a bit                       

- [x]  Data Browser - Filters -  Move arrow to the right so the right and left margin looks the same.

- [x]  Data Browser - Filter Tags - Capitalize the facet.

Facet now name spaced

- [ ]  Data Browser - Filter Tags - Need friendly terms for facets.

- [x]  Data Browser - Download button - remove drop shadow

Button no longer from material 2 library

- [x]  Data Browser - Download button - remove Material animation

- [x]  Data Browser - Download button - needs hover state

- [x]  Data Browser - Download button - heavier type weight

- [ ]  Data Browser - Table - Typography needs to be updated, weights and color

@happyimadesignr Please advise I may have incorrectly inspected the wrong visual!  There are a variety of fonts in the sketch files...

Header on Sketch 0.0 Visuals - Current 1.4 Visuals R3/ 1.5 R3:
Options:
- Montserrat semi bold 12px, black
- Gotham Medium, 12px, letter spacing 0.36px, black
- Gotham Book, 12px, black

I have implemented: Montserrat, now 12px, black, and have beefed weight up to 600.

Table contents
Options: 
Montserrate P3 style, which is Montserrat, regular, 13px or 12px?  P3 style is 13px but I think it is overriden by 12px?
Some Gotham Medium and also Gotham Book styles on the mobile view 13px - ignored them.
I did apply a header font-weight of 500 to first two columns - latter are 400s.  Please confirm if ok.  Appears that on mobile view those two columns have heavier font weight?  Not sure if same on normal view.

Implemented:
Montserrat, 12px, font weight 500 for first two columns, 400 for the remainder,  colours are primary, then 333333 then 666666 for rest

Pls confirm if ok?

@frano-m I'll come back to this                       
         
- [x]  Data Browser - Table - Lines between table line items should be thicker, match design

@happyimadesignr Please advise as they currently meet the spec (1px solid #EAEAEA)

@frano-m you're right thanks               

- [x]  Data Browser - Table - Increase to 15 line items on the table
