### ISSUE TITLE
Remove "May be 1" text from sample and project tab hovers for the cell count estimate column

### ISSUE THREAD

**Issue by ESapenaVentura** [DataBiosphere/data-browser#997]
I am open for discussion, but I think that when you hover over a field in the project's page, it should only display the description of the field, not the guidelines.

This is true for most fields, but when you hover over `cell count estimate`, it displays the guidelines (Which, for this field, is pretty confusing, because I don't think we'll ever get a project with only 1 cell)

![Screenshot 2019-11-19 at 11 14 25](https://user-images.githubusercontent.com/38617863/69141993-c6e1b980-0abd-11ea-89f1-db59f66a177b.png)

It is a minor thing, but since we are in the process of making improvements to the metadata on the webpage, I thought this could be a useful and easy first step.

Tagging @HumanCellAtlas/wranglers just in case they want to say something about this.

**Comment by NoopDog** [comment]
Hi @ESapenaVentura yes this text does not make sense for a project. Thanks for pointing this out. 

We are using the same text for the column in the project tab, samples tab and files tab. There was confusion on why on the files tab we were listing estimated cell count as 1. Thus the extra explanation.

We can adjust so that the different tabs use tab appropriate text. 

Can you tell me if the "May be 1 for well-based assays" is appropriate for the samples tab or is this only appropriate for the files tab?

Cheers and Thanks,
Dave

**Comment by ESapenaVentura** [comment]
>Can you tell me if the "May be 1 for well-based assays" is appropriate for the samples tab or is this only appropriate for the files tab?

The cell count estimate is in the cell suspension schema, so I would say that anything that displays information about specific cell suspensions should include that part of the text. 

My understanding is that the samples tab feeds from specimen from organism, which usually includes several cell suspensions (Specially in well-based assays). If that is the case, I would advise to keep the "May be 1..." only for the files tab.

Thanks for the prompt response!

**Comment by NoopDog** [comment]
@ESapenaVentura Thanks for the clarification. We will remove the "May be 1" text from all but the files tab for the cell count estimate.
