### ISSUE TITLE
Make the project titles in project tab shift-clickable and command-clickable to get into new tabs

### ISSUE THREAD

**Issue by lauraclarke** [DataBiosphere/data-browser#998]
When I right click on a project in the project tab I just seem to end up highlighting a word in the title and I never get an option to open the link in a new tab

Is this expected behaviour?

**Comment by NoopDog** [comment]
HI Laura, 

Yes the project title is not a link so this is the current expected behavior.

If you click  the title  nothing happens. If you double click the title the browser will highlight whatever word you clicked on as is standard browser behavior for non link text. 

Will be no problem to make make the title a link that opens up in a new tab.

Cheers,
Dave

**Comment by lauraclarke** [comment]
I think the fact the text is blue (though I realised it isn't underlined)  and when I hover over them I get a cursor change that looks like it is a link makes me think it is one.

I think making them links is great but if it doesn't fit with the design, the other alternative would be to make it look less like a link

**Comment by NoopDog** [comment]
Sorry I misread your request. I thought you were talking about the project detail page.

On the project list, the blue text titles are definitely links. They are blue, and the cursor changes to a "hand" if you hover over the link.

If you select the link, it takes you to the project detail page for the project.

The standard way to open a link in a new tab is to "command-click" on the link "shift-click" opens in a new window.  (on a mac with similar commands on a PC) 

Now, I see that neither of these commands (command-click or shift-click)  work on the title links on the project page.

The problem is the links are not implemented as real browser links, (they are a fake javascript link) so the browser does not know to apply the default behavior. This is something we can fix.   

Thanks for bringing this up.
D

**Comment by lauraclarke** [comment]
I am using chrome 78.0.3904.97 on mac osx 10.15.1 in case it matters
